# -*- coding: utf-8 -*-
"""Copy of Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nOKVUVCKyXYpZfrzw0HOWGWIM6WSrvVM
"""

from google.colab import files
uploaded=files.upload()

import pandas as pd

df=pd.read_csv('Atlantic_Spain.csv')
df.head()

df.info()
df.describe()
df.isnull().sum()

df.dropna(inplace=True)

import matplotlib.pyplot as plt

df.hist(figsize=(10,8))
plt.show()

df.corr(numeric_only=True)

import seaborn as sns
plt.figure(figsize=(8,6))
sns.heatmap(df.corr(numeric_only=True),annot=True)
plt.show()

df.plot()
plt.show()

df.shape

"""*  the dataset contains 27800 records and 10 columns
*  missing values were handled using data cleaning   techniques
*  correlation analysis shows relationship between variables
*  data visualization helped identity patterns and trends

## Conclusion

This project analyzed the dataset using Python libraries like Pandas, Matplotlib, and Seaborn. Data cleaning was performed to handle missing values, and visualization techniques were used to understand patterns and relationships between variables. The analysis provided meaningful insights and helped in better understanding of the dataset.
"""